version: '3.2'
services:
  backend1:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/usr/src/app'
  backend2:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/usr/src/app'
  backend3:
      build: ./backend
      tty: true
      volumes:
        - './backend/src:/usr/src/app'
  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
          - backend2
          - backend3
      ports:
          - '8080:8080'
volumes:
  backend:
